#!/usr/bin/env bash
# Web servers are the piece of software generating and serving HTML pages

apt-get update -y
apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sh -c 'echo "Hello World!" > /var/www/html/index.html'
sudo touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me http://www.youtube.com/@iyitech permanent;' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server/a error_page 404 /404.html;' /etc/nginx/sites-available/default
service nginx restart
