#!/usr/bin/env bash
# displaying
prog_pid=()
readarray -t prog_pid < < (pgreg -ls -x "bash.*" | grep '4-to_infinity_and_beyond' | cut -d ' ' -f 1)
for ((i = 0; i < "${#prog_pid[@]}"; i++)) do
	kill -s SIGTERM "${prog_pid[i]}"
done

